name: CI Pipeline

on:
  push:
    branches: [solution/josipa_radak]
  pull_request:
    branches: [solution/josipa_radak]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=5s --health-timeout=3s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run tests (pytest)
        run: |
          PYTHONPATH=$(pwd)/src pytest tests/  # Set PYTHONPATH just for the pytest command

      - name: PEP-8 lint check (flake8)
        run: |
          flake8 src/ --max-line-length=100 --exclude=__init__.py

      - name: Build Docker image (check if Dockerfile works)
        run: docker-compose build
